### ISSUE TITLE
missing JSON headers in aw_workspace_report function

### ISSUE THREAD

**Issue by jazzyjens25** [benrwoodard/adobeanalyticsr#156]
Hello, I have successfully set up jwt auth and can run some queries with this package. However, the function aw_workspace_report does not work for me, as I get a 415 error (unsupported media type). The function, I believe (with my limited knowledge), needs to add the headers 

Content Type - application/json
Accept - application/json

to the request to work (at least that's what I can tell based on Adobe Consultant's response and the code of the function). Please, I am entirely new to this and signed up for GitHub just to report this, so please be kind if I am not following protocol here. Thanks very much for this great package.

**Comment by benrwoodard** [comment]
Thanks for the comment on this function. I will look into this and get back to you.

**Comment by benrwoodard** [comment]
Hey jazzyjens25,  I'm really sorry about the long delay. I'm going to assume you have found a solution or another way to accomplish what you were trying to do.  I'll go ahead and answer just in case I might still be able to help. It's only been 4 months.  :( 
The `aw_get_workspace()` function has a hard time handling a lot of the more complex queries that Analysis Workspace is able to create. I'm assuming that your request includes some of the in-freeform-table filtered metrics or something but wouldn't be able to know for sure unless you were able to share the API call with me.  Unfortunately, that `debug` argument isn't even available on this function call so the only way for me to debug this with you is for you to send the JSON file, if you are comfortable doing that.
