### ISSUE TITLE
date range discrepancy in aw_freeform_table versus JSON from Adobe Workspace freeform table

### ISSUE THREAD

**Issue by pavilaba** [benrwoodard/adobeanalyticsr#159]
Hi, when comparing the first 50K rows from the freeform created in Adobe Workspace UI for 2023-06-30 versus the first 50K rows from aw_freeform_table(..., date_range = c(2023-06-30,2023-06-30)) the dimension values were the same but the metrics values were a little bit lower (1% lower for the metrics I checked). 

So I decided to look into it and noticed that the JSON request from the Workspace UI set the date range in:

2023-06-30T00:00:00:000/2023-07-01T00:00:00:000

while aw_freeform_table set the explicit date range in:

2023-06-30T00:00:00:000/2023-06-30T23:59:59:999

I know it´s a minor deviation originated from a milisecond but I wanted to ask if there is a way I can set the date range parameter with this milisecond precision

**Comment by benrwoodard** [comment]
Hey Pedro!  If you pass the POSIXct version of the dates into the function it will recognize that date-time format and use it in the request.  Try something like this:
`dr <- c(as.POSIXct('2023-04-30 02:00:00:000'), as.POSIXct('2023-05-31 02:01:01:000'))`
Then pass `dr` as the `date_range` argument value.  It should work as you expect.

**Comment by pavilaba** [comment]
Hi Ben, thanks for the answer. I tried this and works fine.
