### ISSUE TITLE
Long Runtime for One Day's Data Retrieval

### ISSUE THREAD

**Issue by akml12** [benrwoodard/adobeanalyticsr#160]
I am writing to report a runtime issue with the aw_freeform_table() function in the adobeanalyticsr package.

Problem:
When using the aw_freeform_table() function to retrieve data for a single day, the runtime is excessively long, taking more than 10 minutes to complete. 

Additional Notes:

I have already attempted to optimize the code by specifying a smaller date range, and ordering dimensions strategically, but the issue persists. My 'top' parameter is set as c(0,500,500) my dimensions are (date,trackingcode,campaign name)
I have validated the metrics and dimensions used in the query to avoid unnecessary API calls for validation.

Expected Behavior:
The function should fetch data for the specified date within a reasonable timeframe, typically a few seconds or a minute at most.

Actual Behavior:
The data retrieval process takes more than 10 minutes, which significantly impacts the efficiency of data analysis workflows.

Please let me know if there are any recommended steps to further optimize the data retrieval process and reduce the runtime for fetching data for a single day. I am eager to hear your insights on how to address this issue and improve the performance of the aw_freeform_table() function.

**Comment by benrwoodard** [comment]
@akml12 Did the answer solve this for you?

**Comment by akml12** [comment]
I got the logic. But my requirements will need to apply multiple dimensions breakdown and for this the runtime is very high
________________________________
