### ISSUE TITLE
Filtering in a date range 

### ISSUE THREAD

**Issue by aparada96** [benrwoodard/adobeanalyticsr#161]
I have the following code below. Is there a way to filter the selected date range in R but only capture specific hours? For example, I want to apply a date range filter for 30 days but only select results between the hours of 7pm and 10pm. 

```
aw_freeform_table(rsid = 'worksite-prod',
                           date_range = c("2023-08-01", "2023-08-30"),    
                           metrics =  c("visitors","videototaltime"),
                           dimensions = c("videoname",'evar18','daterangeday'),
                           search =  "CONTAINS 'Baseball'",
                           prettynames = T,
                           segmentId = "s12345",
                           top = 30)
```

I know that I can filter for a specific time frame by applying:` date_range = as.POSIXct(c("2023-08-29T19:00:00", "2023-08-29T22:00:00"), format = "%Y-%m-%dT%H:%M:%S")`, but I wonder if there's a way to do this where I wouldn't have to apply/run this 30 times (for the 30 days). Thanks!

**Comment by charlie-gallagher** [comment]
There's a dimension called "Hour of Day" (api ID is `timeparthourofday`). You could make a segment for the hours that you want and apply that to your query with the segmentId argument. Alternatively you could request the hour of the day as a dimension, it all just depends on purpose

**Comment by charlie-gallagher** [comment]
Here's a quick version if you want an hourly breakdown:

```r
aw_freeform_table(dimensions = 'timeparthourofday', search = "( CONTAINS '7:00 PM' ) OR ( CONTAINS '8:00 PM')")
```

**Comment by charlie-gallagher** [comment]
For a segment, this seems to work correctly

<img width="698" alt="Screenshot 2023-08-30 at 4 35 56 PM" src="https://github.com/benrwoodard/adobeanalyticsr/assets/58119387/de6dfdc3-c672-4686-a5ba-443387cc4e3d">

**Comment by benrwoodard** [comment]
@aparada96 did @charlie-gallagher's solution solve this for you?

**Comment by benrwoodard** [comment]
closing out due to inactivity
