### ISSUE TITLE
adobeanalyticsr.com domain has expired

### ISSUE THREAD

**Issue by zugbug007** [benrwoodard/adobeanalyticsr#182]
Hi All,

The URI redirect domain for authentication (where you copy/paste the auth token output from) seems to have expired. The token is still available in the URL field of the browser but this could be a potential security risk. 
Flagging so the domain can be updated or the URI instructions on the project page can be updated to something more suitable.

Cheers
Alan

**Comment by benrwoodard** [comment]
Hey Allen,

Thanks for the heads up. We were able to get this issue resolved.
