### ISSUE TITLE
0 results getting queried/returned when a daterange dimension is in a non-1st position

### ISSUE THREAD

**Issue by gilliganondata** [benrwoodard/adobeanalyticsr#36]
This was identified when I was simply exploring the difference in runtimes from ordering my dimensions in a "smart" way versus in an "obvious" (but slower, based on the API workings) way. Both examples were intended to return "complete" data.

This was for a 30-day period.

```
df_fast <- aw_freeform_report(company_id = company_id,
                              rsid = rsid,
                              date_range = c(start_date, end_date),
                              dimensions = c("mobiledevicetype", "lasttouchchannel", "daterangeday"),
                              metrics = c("visits", "pageviews", "orders", "revenue"),
                              top = c(10, 30, 0))

df_slow <- aw_freeform_report(company_id = company_id,
                              rsid = rsid,
                              date_range = c(start_date, end_date),
                              dimensions = c("daterangeday", "lasttouchchannel", "mobiledevicetype"),
                              metrics = c("visits", "pageviews", "orders", "revenue"),
                              top = c(0, 30, 10))
```

As expected, putting `daterangeday` last was _much_ faster (4X). 

**But**, `df_fast` also had more rows than `df_slow`. Further investigation turned up that `df_fast` had a number of rows with "0" values for all of the metrics.

The _totals_ (sum) for each metric were identical across the two data frames.

Below are some of the "all zeros:"

![image](https://user-images.githubusercontent.com/19396775/100099546-96013680-2e2d-11eb-9a57-429e4ddf25dc.png)

I think what is going on is that, for `daterange` values, the API ensures that it returns a value for every date increment in the date range. Theoretically, this could occur for a very low-incidence metric even if a `daterange` dimension is at the top level. But, if a `daterange` value is farther down—which makes for more efficient querying—it's more likely to occur.

Is this just a lower-priority something to document? (Or maybe Adobe has already documented it?

**Comment by charlie-gallagher** [comment]
Since this appears to be an artifact of Workspace and not the package, can we close @gilliganondata @benrwoodard ?

**Comment by gilliganondata** [comment]
Yep. That makes sense. Closing it.
