### ISSUE TITLE
Time handling in the freeform_report() function

### ISSUE THREAD

**Issue by benrwoodard** [benrwoodard/adobeanalyticsr#6]
### scenarios 
1. user includes 'daterangeday' in the dimension list of 3 dimensions and then adds 'top=(2, 5)' to the list for the limits expecting the data granularity to calculated.
2. User includes "timegranularity" attribute and expects all dimensions to be broken down by that type of granularity.  
3. User adds 'daterange...." anywhere in the dimension list and expects the breakdown to result in all the corresponding rows as a result

**Comment by charlie-gallagher** [comment]
@benrwoodard I'm going to close this since it seems like you've captured this behavior already. If there's anything else we can make a new issue for it
