### ISSUE TITLE
aw_freeform_table() - provide actual runtime when query is complete

### ISSUE THREAD

**Issue by gilliganondata** [benrwoodard/adobeanalyticsr#69]
Current example of messages when running `aw_freeform_table()`:

```
Estimated runtime: 318.4sec./5.31min.
1 of 398 possible data requests complete. Starting the next 397 requests.
A total of 1985 rows have been pulled.
```

Since queries will often get run multiple times with no or minimal adjustments, it would be nice to have one more line that reports how long the actual runtime was:

```
Estimated runtime: 318.4sec./5.31min.
1 of 398 possible data requests complete. Starting the next 397 requests.
A total of 1985 rows have been pulled.
Actual runtime: 284.3/ 4.73min.
```

**Comment by charlie-gallagher** [comment]
As mentioned in Issue #96, I've added a progress bar, which features a timer tracking how long the query has been running
