### ISSUE TITLE
aw_freeform_table() - provide periodic query count updates

### ISSUE THREAD

**Issue by gilliganondata** [benrwoodard/adobeanalyticsr#70]
A current example of the messages when running `aw_freeform_table()`:

```
Estimated runtime: 318.4sec./5.31min.
1 of 398 possible data requests complete. Starting the next 397 requests.
A total of 1985 rows have been pulled.
```

So, there's some information provided up front: an estimated runtime and then the fact that the first data request has run. But...then there's nothing.

It would be nice to get periodic updates on progress—not necessarily every request, but, based on the estimated total requests, every request or every 5 requests or every 10 requests. So, in the example above, logic could be that there are an estimated 397 requests, and that's greater than 200, so an "every 50" increment would be used:

```
Estimated runtime: 318.4sec./5.31min.
1 of 398 possible data requests complete. Starting the next 397 requests.
50 of 398 possible data requests complete. Starting the next 348 requests.
100 of 398 possible data requests complete. Starting the next 298 requests.
150 of 398 possible data requests complete. Starting the next 248 requests.
200 of 398 possible data requests complete. Starting the next 198 requests.
250 of 398 possible data requests complete. Starting the next 148 requests.
300 of 398 possible data requests complete. Starting the next 98 requests.
350 of 398 possible data requests complete. Starting the next 48 requests.
398 of 398 possible data requests complete. Starting the next 397 requests.
A total of 1985 rows have been pulled.
```

This would need some additional thought. It also could be, "provide ~15 updates" so the total estimated would be divided by 15 and then that's the increment that would then be used.

Alternative, a "messages" argument could have options to include these notifications or not.

**Comment by charlie-gallagher** [comment]
Similar to #96, will be addressed by the progress bar
