### ISSUE TITLE
Is there a Rtools dependancy?

### ISSUE THREAD

**Issue by ankitnagarsheth** [benrwoodard/adobeanalyticsr#72]
@benrwoodard 

I am using R Version 1.3.959. When installing it is showing a namespace issue. Have you seen this error before?

![56b72638-5a34-488b-a1eb-e851242b6a5d](https://user-images.githubusercontent.com/16673852/105911179-e9dbf780-5ff7-11eb-9470-fdcf5b470528.png)

**Comment by benrwoodard** [comment]
This sounds like a punt but try restarting the r session. Looks like that has fixed a lot of these types of errors. If that doesn't work then let me know.

**Comment by ankitnagarsheth** [comment]
Thanks, Ben!! Looks like I am having other issues now.

`Installing packages into ‘C:/Users/nagar/Documents/R/win-library/4.0’
(as ‘lib’ is unspecified)
Error: Failed to install 'adobeanalyticsr' from GitHub:`

`I used install_github('benrwoodard/adobeanalyticsr') `

**Comment by benrwoodard** [comment]
Can you send a screenshot of the file or copy and paste all the code leading up to the error?

**Comment by benrwoodard** [comment]
Can you send a screenshot of the file or copy and paste all the code leading up to the error?

**Comment by benrwoodard** [comment]
@ankitnagarsheth were you able to figure out the error?

**Comment by ankitnagarsheth** [comment]
@benrwoodard  Below is the reprex code leading up to the error


`# Title:    Adobe Analytics R 2.0
# File:     analysis.R
# DATE:       Jan 26 2021
# Project:  AdobeAnalyticsR

# INSTALL AND LOAD PACKAGES ################################


# Install pacman ("package manager") if needed
if (!require("pacman")) install.packages("pacman")
#> Loading required package: pacman

# pacman must already be installed; then load contributed
# packages (including pacman) with pacman
pacman::p_load(pacman,rio,tidyverse,DataExplorer,DT,reprex)


# LOAD THE PACKAGE AND AUTHENTICATE################################

# Install devtools from CRAN
install.packages("devtools")
#> Installing package into 'C:/Users/nagara/Documents/R/win-library/4.0'
#> (as 'lib' is unspecified)
#> Warning: unable to access index for repository http://www.stats.ox.ac.uk/pub/RWin/bin/windows/contrib/4.0:
#>   cannot open URL 'http://www.stats.ox.ac.uk/pub/RWin/bin/windows/contrib/4.0/PACKAGES'
#> package 'devtools' successfully unpacked and MD5 sums checked
#> 
#> The downloaded binary packages are in
#>  C:\Users\nagara\AppData\Local\Temp\RtmpK0s009\downloaded_packages
# install.packages("githubinstall")
# 



# Install adobeanayticsr from github
devtools :: install_github('benrwoodard/adobeanalyticsr') 
#> Downloading GitHub repo benrwoodard/adobeanalyticsr@HEAD
#> stringi    (1.4.6    -> 1.5.3   ) [CRAN]
#> magrittr   (1.5      -> 2.0.1   ) [CRAN]
#> glue       (1.4.1    -> 1.4.2   ) [CRAN]
#> xfun       (0.14     -> 0.20    ) [CRAN]
#> digest     (0.6.25   -> 0.6.27  ) [CRAN]
#> vctrs      (0.3.2    -> 0.3.6   ) [CRAN]
#> rlang      (0.4.7    -> 0.4.10  ) [CRAN]
#> fansi      (0.4.1    -> 0.4.2   ) [CRAN]
#> cli        (2.0.2    -> 2.2.0   ) [CRAN]
#> colorspace (1.4-1    -> 2.0-0   ) [CRAN]
#> R6         (2.4.1    -> 2.5.0   ) [CRAN]
#> labeling   (0.3      -> 0.4.2   ) [CRAN]
#> pillar     (1.4.4    -> 1.4.7   ) [CRAN]
#> tibble     (3.0.3    -> 3.0.5   ) [CRAN]
#> diffobj    (NA       -> 0.3.3   ) [CRAN]
#> rstudioapi (0.11     -> 0.13    ) [CRAN]
#> rprojroot  (1.3-2    -> 2.0.2   ) [CRAN]
#> waldo      (NA       -> 0.2.3   ) [CRAN]
#> ps         (1.3.3    -> 1.5.0   ) [CRAN]
#> brio       (NA       -> 1.1.1   ) [CRAN]
#> testthat   (2.3.2    -> 3.0.1   ) [CRAN]
#> sys        (3.3      -> 3.4     ) [CRAN]
#> generics   (0.0.2    -> 0.1.0   ) [CRAN]
#> isoband    (0.2.1    -> 0.2.3   ) [CRAN]
#> Rcpp       (1.0.4.6  -> 1.0.6   ) [CRAN]
#> cpp11      (NA       -> 0.2.5   ) [CRAN]
#> dplyr      (1.0.0    -> 1.0.3   ) [CRAN]
#> openssl    (1.4.1    -> 1.4.3   ) [CRAN]
#> BH         (1.72.0-3 -> 1.75.0-0) [CRAN]
#> knitr      (1.28     -> 1.31    ) [CRAN]
#> ggplot2    (3.3.2    -> 3.3.3   ) [CRAN]
#> lubridate  (1.7.9    -> 1.7.9.2 ) [CRAN]
#> tidyr      (1.1.0    -> 1.1.2   ) [CRAN]
#> purrrlyr   (NA       -> 0.0.7   ) [CRAN]
#> Installing 34 packages: stringi, magrittr, glue, xfun, digest, vctrs, rlang, fansi, cli, colorspace, R6, labeling, pillar, tibble, diffobj, rstudioapi, rprojroot, waldo, ps, brio, testthat, sys, generics, isoband, Rcpp, cpp11, dplyr, openssl, BH, knitr, ggplot2, lubridate, tidyr, purrrlyr
#> Error: Failed to install 'adobeanalyticsr' from GitHub:
#>   (converted from warning) packages 'tibble', 'dplyr', 'ggplot2', 'tidyr' are in use and will not be installed

# remotes::install_github("benrwoodard/adobeanalytics")

# Load the pacakge
library(adobeanalyticsr) 
#> Error in library(adobeanalyticsr): there is no package called 'adobeanalyticsr'
library(devtools)
#> Warning: package 'devtools' was built under R version 4.0.3
#> Loading required package: usethis
#> Warning: package 'usethis' was built under R version 4.0.3
  
  
# Install adobeanayticsr from github
devtools::install_github('benrwoodard/adobeanalyticsr') 
#> Downloading GitHub repo benrwoodard/adobeanalyticsr@HEAD
#> stringi    (1.4.6    -> 1.5.3   ) [CRAN]
#> magrittr   (1.5      -> 2.0.1   ) [CRAN]
#> glue       (1.4.1    -> 1.4.2   ) [CRAN]
#> xfun       (0.14     -> 0.20    ) [CRAN]
#> digest     (0.6.25   -> 0.6.27  ) [CRAN]
#> vctrs      (0.3.2    -> 0.3.6   ) [CRAN]
#> rlang      (0.4.7    -> 0.4.10  ) [CRAN]
#> fansi      (0.4.1    -> 0.4.2   ) [CRAN]
#> cli        (2.0.2    -> 2.2.0   ) [CRAN]
#> colorspace (1.4-1    -> 2.0-0   ) [CRAN]
#> R6         (2.4.1    -> 2.5.0   ) [CRAN]
#> labeling   (0.3      -> 0.4.2   ) [CRAN]
#> pillar     (1.4.4    -> 1.4.7   ) [CRAN]
#> tibble     (3.0.3    -> 3.0.5   ) [CRAN]
#> diffobj    (NA       -> 0.3.3   ) [CRAN]
#> rstudioapi (0.11     -> 0.13    ) [CRAN]
#> rprojroot  (1.3-2    -> 2.0.2   ) [CRAN]
#> waldo      (NA       -> 0.2.3   ) [CRAN]
#> ps         (1.3.3    -> 1.5.0   ) [CRAN]
#> brio       (NA       -> 1.1.1   ) [CRAN]
#> testthat   (2.3.2    -> 3.0.1   ) [CRAN]
#> sys        (3.3      -> 3.4     ) [CRAN]
#> generics   (0.0.2    -> 0.1.0   ) [CRAN]
#> isoband    (0.2.1    -> 0.2.3   ) [CRAN]
#> Rcpp       (1.0.4.6  -> 1.0.6   ) [CRAN]
#> cpp11      (NA       -> 0.2.5   ) [CRAN]
#> dplyr      (1.0.0    -> 1.0.3   ) [CRAN]
#> openssl    (1.4.1    -> 1.4.3   ) [CRAN]
#> BH         (1.72.0-3 -> 1.75.0-0) [CRAN]
#> knitr      (1.28     -> 1.31    ) [CRAN]
#> ggplot2    (3.3.2    -> 3.3.3   ) [CRAN]
#> lubridate  (1.7.9    -> 1.7.9.2 ) [CRAN]
#> tidyr      (1.1.0    -> 1.1.2   ) [CRAN]
#> purrrlyr   (NA       -> 0.0.7   ) [CRAN]
#> Installing 34 packages: stringi, magrittr, glue, xfun, digest, vctrs, rlang, fansi, cli, colorspace, R6, labeling, pillar, tibble, diffobj, rstudioapi, rprojroot, waldo, ps, brio, testthat, sys, generics, isoband, Rcpp, cpp11, dplyr, openssl, BH, knitr, ggplot2, lubridate, tidyr, purrrlyr
#> Error: Failed to install 'adobeanalyticsr' from GitHub:
#>   (converted from warning) packages 'tibble', 'dplyr', 'ggplot2', 'tidyr' are in use and will not be installed
Created on 2021-01-28 by the reprex package (v0.3.0)`

**Comment by benrwoodard** [comment]
I think you will need to update the tidyverse package.  Try tidyverse::tidyverse_update()

**Comment by ankitnagarsheth** [comment]
@benrwoodard Had to reinstall RStudio and now it works. :) Thanks for your help
