### ISSUE TITLE
Paid License Required?

### ISSUE THREAD

**Issue by j450h1** [benrwoodard/adobeanalyticsr#73]
Can you confirm a paid license is required in order to connect to the Adobe Analytics API when setting up the **Adobe Console API Project** here https://console.adobe.io/integrations?

If so, how do I purchase this subscription, is the subscription tied to my account or maybe the organization I'm working with?

**Comment by benrwoodard** [comment]
It would be through the organization your account is associated with.

**Comment by j450h1** [comment]
Got it thanks. One of my colleagues helped me set it up. I guess his account had the proper permission.
