### ISSUE TITLE
finalmnames error message without metric filters aw_workspace_report() function

### ISSUE THREAD

**Issue by kultgenj** [benrwoodard/adobeanalyticsr#79]
When attempting to use the `aw_workspace_report()` function on a JSON file without 'metric filters' one receives the following error '`object 'finalmnames' not found`'.

From a prioritization perspective this is likely low value as one could use `aw_freeform_table()` to successfully fetch the 'same' request.

Image of error message below.  The text that is within the sample json file is within the text file below (can't  upload json file here).

![image](https://user-images.githubusercontent.com/7227906/107867564-69aff180-6e41-11eb-8c34-eda0fda9b887.png)

[sampleRequest.txt](https://github.com/benrwoodard/adobeanalyticsr/files/5976947/sampleRequest.txt)

**Comment by benrwoodard** [comment]
Did you attempt to edit the json text from the oberon debugger?

**Comment by kultgenj** [comment]
I did not.

Copied it from Chrome, pasted into Sublime, and saved the file.
The only edg-ish thing I can think of here is that it is a Virtual report suite.  Not sure if the presence of an underscore could break something scenario based?

Here is the request if it is helpful (rather than seeing it within the text file):
{
```
    "rsid": "vrs_classib_carscomresponsivesit",
    "globalFilters": [
        {
            "type": "dateRange",
            "dateRange": "2021-01-01T00:00:00.000/2021-02-01T00:00:00.000"
        }
    ],
    "metricContainer": {
        "metrics": [
            {
                "columnId": "0",
                "id": "metrics/visitors"
            },
            {
                "columnId": "1",
                "id": "metrics/visits",
                "sort": "desc"
            },
            {
                "columnId": "2",
                "id": "metrics/pageviews"
            }
        ]
    },
    "dimension": "variables/lasttouchchannel",
    "settings": {
        "countRepeatInstances": true,
        "limit": 50,
        "page": 0,
        "nonesBehavior": "return-nones"
    },
    "statistics": {
        "functions": [
            "col-max",
            "col-min"
        ]
    }
}
```
