### ISSUE TITLE
Provide an error message if an incompatible segment is used in aw_workspace_report() function

### ISSUE THREAD

**Issue by kultgenj** [benrwoodard/adobeanalyticsr#80]
Currently when an incompatible segment is used as a **metric filter** within the `aw_workspace_report()` function there isn't an indication to the user.  Nor is a column with values of zero returned.  Instead a user receives fewer columns than requested.
This might have to do with recent changes to the AW UI with appear to deemphasize that type of messaging in multi-report suite projects.

Admittedly this is likely lower priority as I only noticed it when running a loop through different suites.

**Comment by benrwoodard** [comment]
More support is needed for cross report suite error handling and enhancement in support for multi-rsid function calls.

**Comment by charlie-gallagher** [comment]
@benrwoodard this was a bug in the previous implementation, so I'm going to close this. If the same bug persisted in the current version, we can re-open it or start a new ticket.
