### ISSUE TITLE
aw_token() alternative for non-interactive/server automation use cases?

### ISSUE THREAD

**Issue by j450h1** [benrwoodard/adobeanalyticsr#90]
Is it possible and/or are there plans to develop a way to authenticate to support non-interactive use cases?

Even a workaround where a token could be generated fully programmatically without having to manually login in to the browser every 24 hours would be a good option.

**Comment by benrwoodard** [comment]
This has been an ongoing discussion as we have developed the package. According to Adobe's documentation it sounds like the authentication you would want would be the JSON Web Token (JWT) authentication.  It's for situations requiring server-to-server, service-token, or other long-running authentications.  It also enables a much more specific level of permissions.

While the JWT authentication option is not currently supported in the package it is one that we want to implement as an option in the near future.  

@j450h1 Would you be able to elaborate more on the use case for this different type of authentication?

**Comment by j450h1** [comment]
Thanks for clarifying - so it is a possibility. 

Yes, my use case is I'm pushing data into Google BigQuery to support dashboards and I want to bring in new data on a daily basis. I'm planning to use a Google Cloud service such as Compute Engine to actually run this code. 

Of course, it is not possible right now as would need to manually refresh the token and push the new token to the VM. Actually, that leads me to maybe a temporary workaround of allowing the user to change the default expiry time to more than 24 hours? If I had to only refresh the token once a month for example, that would be a good compromise. Otherwise I will need to revert back to the old API and package due to this limitation.

**Comment by charlie-gallagher** [comment]
Excited to say the newest GitHub version of the package supports JWT authentication
