### ISSUE TITLE
Cannot regenerate token

### ISSUE THREAD

**Issue by shannonhlo** [benrwoodard/adobeanalyticsr#94]
Hi, I'm trying to regenerate my authorization token after the initial one expired. Unfortunately I can't get the browser window to appear after running `aw_token()` as specified in the [documentation here](https://github.com/benrwoodard/adobeanalyticsr#3-get-your-authorization-token). I get the output below instead, but that doesn't help regenerate the authentication token. Am I missing something?
![adobe_api_error](https://user-images.githubusercontent.com/40256709/118323662-cdd06900-b4b5-11eb-8d4d-742b00053e30.png)

**Comment by shannonhlo** [comment]
Additional note: I've ocnfirmed that the client ID and secret in the `.Renviron` file are correct

**Comment by benrwoodard** [comment]
Hey Shannon,  
Unfortunately, Adobe hasn't enabled the use of the refresh token using oAuth even though it is part of the token. This means that there is some confusion in the authorization process when the token is expired. There are 2 basic ways to overcome this. The first is to simply delete the 'aa.oauth' file in your home directory and run `aw_token()` again.  This will trigger the re-authorization dance again.  The second way, my preferred way, is to simply run the `get_me()` function again after getting the 401 error.  Most of the time this will also restart the oAuth dance.

**Comment by shannonhlo** [comment]
Thank you for the details Ben, I've refreshed the token successfully!
