### ISSUE TITLE
aw_freeform_table - add argument to output API call volume messages

### ISSUE THREAD

**Issue by gilliganondata** [benrwoodard/adobeanalyticsr#96]
Example of the current behavior:

```
Estimated runtime: 2400.8sec./40.01min.
1 of 3001 possible data requests complete. Starting the next 1346 requests.
```

The message above gets printed to the console...and then it's just a waiting game. There is no feedback as to whether the request is at 300 or 1,200.

Proposal: add an argument to `aw_freeform_table` that allows the user to specify having an update to the console every "X" requests. I don't think you want to just pick a flat number, as someone may know there will be 20-30 requests and want to see  an update every 5 requests, or they may think it's going to be more like 10,000 and want an update every 500.

The argument could be: `track_requests = 0` as the default, and any value that is put in means that each chunk of data requests will print to the console. For instance, if `track_requests = 300`:

```
Estimated runtime: 2400.8sec./40.01min.
1 of 3001 possible data requests complete. Starting the next 1346 requests.
300 of 1,347 requests completed. 
600 of 1,347 requests completed.
...
```

The second number could change or still be "possible" or "estimated" or "up to" depending on how many dimensions are in the request.

**Comment by charlie-gallagher** [comment]
I've added a progress bar in the `jwtadd` branch, so this may be included in an upcoming version of the package
