### ISSUE TITLE
Authorization process issue

### ISSUE THREAD

**Issue by kultgenj** [benrwoodard/adobeanalyticsr#97]
When running the aw_token() command I am getting routed to the following url:

https://ims-na1.adobelogin.com/ims//authorize/v2?client_id=&scope=openid%2CAdobeID%2Cread_organizations%2Cadditional_info.projectedProductContext%2Cadditional_info.job_function&redirect_uri=https%3A%2F%2Fadobeanalyticsr.com%2Ftoken_result.html&response_type=code

And receiving an error message 'There was an error with this action. Try again later.'

Today is the first day I received this error.
Not sure if it is caused by the consecutive '/' charters after ims?

**Comment by benrwoodard** [comment]
The missing "client_id=" parameter is most likely the tell to the issue.  This means either the `client_id` and `client_secret` arguments were not provided in the function call and/or the .Renviron variables are not set.

Make sure you have `AW_CLIENT_ID` and `AW_CLIENT_SECRET` set in the .Renviron file and then restart R or supply the values, "client_id = " and "client_secret = ", in the `aw_token()` function arguments.

If you can run `Sys.getenv("AW_CLIENT_ID")` and `Sys.getenv("AW_CLIENT_SECRET")` and it returns the accurate values then let me know. If not then set those and rerun the `aw_token()` function and it should return the token.

**Comment by PatLittle** [comment]
I was just struggling with this or a similar issue for the last ~45 minutes or so. The issue I was having was I had an old version of the aa.outh file in my working directory. As soon as I deleted that old aa.outh file the authentication instructions worked seamlessly. 
Hopefully useful info for anyone who might stumble on this issue.
